name: interfaces-env

channels:
    - auto-mech
    - conda-forge

dependencies:
    - python=3.7
    - pybind11
    - numpy
    - pytest
    - pytest-cov
    - future
    - flake8
    - pylint
    - conda-forge::qcelemental
    - auto-mech::automol
    - auto-mech::autoparse
