# cmd: conda build . -c auto-mech -c conda-forge
package: 
    name: interfaces
    version: "0.2.0"
 
source:
    path: .

requirements:
    build:
        - python
    run:
        - python
        - numpy
        - mako
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - conda-forge::qcelemental
        - auto-mech::automol
        - auto-mech::autoparse
